name: emababyspa
description: "An App to Manage Ema Mom Kids Babyspa."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # state management
  get: ^4.7.2
  # network
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0

  # storage for storing state
  get_storage: ^2.1.1

  # UI
  flutter_svg: ^2.1.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

  #utils
  logger: ^2.5.0
  connectivity_plus: ^6.1.4
  equatable: ^2.0.7
  url_launcher: ^6.3.1

  # authentication
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  package_info_plus: ^8.3.0
  device_info_plus: ^11.4.0
  path: ^1.9.1
  http_parser: ^4.1.2
  table_calendar: ^3.2.0
  lottie: ^3.3.1
  fl_chart: ^1.0.0
  onesignal_flutter: ^5.3.4
  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/animation/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-VariableFont_wght.ttf
          style: normal
        - asset: assets/fonts/JosefinSans-Italic-VariableFont_wght.ttf
          style: italic
    - family: DeliusSwashCaps
      fonts:
        - asset: assets/fonts/DeliusSwashCaps-Regular.ttf
          style: normal

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
